### ISSUE TITLE
Image no longer works after recent push - java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by mlamm** [woahbase/alpine-activemq#1]
There has been a push to https://hub.docker.com/r/woahbase/alpine-activemq. Since then the image doesnt work for me anymore:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
INFO: Loading '/opt/activemq/bin/env'
INFO: Using java '/usr/lib/jvm/java-1.8-openjdk/bin/java'
[services.d] done.
INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)
INFO: Creating pidfile /opt/activemq/data/activemq.pid
Java Runtime: Oracle Corporation 1.8.0_201 /usr/lib/jvm/java-1.8-openjdk/jre
  Heap sizes: current=62976k  free=58698k  max=932352k
    JVM args: -Xms64M -Xmx1G -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/activemq/conf/login.config -Dcom.sun.management.jmxremote -Djava.awt.headless=true -Djava.io.tmpdir=/opt/activemq/tmp -Dactivemq.classpath=/opt/activemq/conf:/opt/activemq/../lib/: -Dactivemq.home=/opt/activemq -Dactivemq.base=/opt/activemq -Dactivemq.conf=/opt/activemq/conf -Dactivemq.data=/opt/activemq/data
Extensions classpath:
  [/opt/activemq/lib,/opt/activemq/lib/camel,/opt/activemq/lib/optional,/opt/activemq/lib/web,/opt/activemq/lib/extra]
ACTIVEMQ_HOME: /opt/activemq
ACTIVEMQ_BASE: /opt/activemq
ACTIVEMQ_CONF: /opt/activemq/conf
ACTIVEMQ_DATA: /opt/activemq/data
Loading message broker from: xbean:activemq.xml
 INFO | Refreshing org.apache.activemq.xbean.XBeanBrokerFactory$1@5442a311: startup date [Mon Mar 18 14:46:29 GMT 2019]; root of context hierarchy
 INFO | Using Persistence Adapter: KahaDBPersistenceAdapter[/opt/activemq/data/kahadb]
 INFO | PListStore:[/opt/activemq/data/localhost/tmp_storage] started
 INFO | Apache ActiveMQ 5.15.8 (localhost, ID:7fd3e10659f7-34205-1552920390990-0:1) is starting
 INFO | Listening for connections at: tcp://7fd3e10659f7:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600
 INFO | Connector openwire started
 INFO | Listening for connections at: amqp://7fd3e10659f7:5672?maximumConnections=1000&wireFormat.maxFrameSize=104857600
 INFO | Connector amqp started
 INFO | Listening for connections at: stomp://7fd3e10659f7:61613?maximumConnections=1000&wireFormat.maxFrameSize=104857600
 INFO | Connector stomp started
 INFO | Listening for connections at: mqtt://7fd3e10659f7:1883?maximumConnections=1000&wireFormat.maxFrameSize=104857600
 INFO | Connector mqtt started
 INFO | Starting Jetty server
 INFO | Creating Jetty connector
 WARN | ServletContext@o.e.j.s.ServletContextHandler@7b8b43c7{/,null,STARTING} has uncovered http methods for path: /
 INFO | Listening for connections at ws://7fd3e10659f7:61614?maximumConnections=1000&wireFormat.maxFrameSize=104857600
 INFO | Connector ws started
 INFO | Apache ActiveMQ 5.15.8 (localhost, ID:7fd3e10659f7-34205-1552920390990-0:1) started
 INFO | For help or more information please see: http://activemq.apache.org
 INFO | No Spring WebApplicationInitializer types detected on classpath
 WARN | FAILED SslContextFactory@3efe7086(null,null): java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:188)[:1.8.0_201]
        at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:152)[:1.8.0_201]
        at sun.security.ssl.SSLSessionImpl.<clinit>(SSLSessionImpl.java:79)[:1.8.0_201]
        at sun.security.ssl.SSLEngineImpl.init(SSLEngineImpl.java:364)[:1.8.0_201]
        at sun.security.ssl.SSLEngineImpl.<init>(SSLEngineImpl.java:344)[:1.8.0_201]
        at sun.security.ssl.SSLContextImpl$AbstractTLSContext.createSSLEngineImpl(SSLContextImpl.java:557)[:1.8.0_201]
        at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:199)[:1.8.0_201]
        at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:329)[:1.8.0_201]
```

**Comment by lapnapra** [comment]
Hi, 

From the build logs, it looks like there was this file `/usr/lib/libnss3.so` missing, it's provided by the package `nss`. I've added it to be installed explicitly, so a fresh image should be up by now. Let me know if the problem still persists in this one.

Also, I had to bump the version to 5.15.9 because the mirror I'm using doesn't have the 5.15.8 jars anymore.

**Comment by mlamm** [comment]
Thank you @lapnapra, it's working again.
